"""Hard planning and call budgets shared by schemas and the planner."""

MAX_PLAN_STEPS = 8
MAX_EXECUTION_STEPS = 20
MAX_RETRY_COUNT = 1
MAX_MODEL_ATTEMPTS = MAX_RETRY_COUNT + 1
MAX_TOOL_ATTEMPTS = MAX_RETRY_COUNT + 1
MAX_PLANNER_REPAIR_CHARS = 4_000
MAX_SEARCH_RESULTS = 10
MAX_SEARCH_QUERY_CHARS = 600
MAX_SEARCH_QUERY_WORDS = 75
SEARCH_TIMEOUT_SECONDS = 8
SEARCH_MAX_RESPONSE_BYTES = 1_000_000
URL_FETCH_TIMEOUT_SECONDS = 10
URL_FETCH_MAX_RESPONSE_BYTES = 1_000_000
URL_FETCH_MAX_TEXT_CHARS = 20_000
URL_FETCH_MAX_REDIRECTS = 5
CALCULATOR_MAX_EXPRESSION_CHARS = 256
CALCULATOR_MAX_AST_NODES = 64
